// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2ZGlbCowxyQmdwhTUugLPCqyPyzy1yeI',
    appId: '1:409695014933:web:a60e56d0107b71dd05fe1c',
    messagingSenderId: '409695014933',
    projectId: 'red-social-c786b',
    authDomain: 'red-social-c786b.firebaseapp.com',
    storageBucket: 'red-social-c786b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWTRKTQYEd55MygbHSlFmKU4nENRRDDgE',
    appId: '1:409695014933:android:480a41c47c69bb6b05fe1c',
    messagingSenderId: '409695014933',
    projectId: 'red-social-c786b',
    storageBucket: 'red-social-c786b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZYKaYwfCEgnsmUfXB-kU_3GvKQtdhEFY',
    appId: '1:409695014933:ios:637be17ad428bb5c05fe1c',
    messagingSenderId: '409695014933',
    projectId: 'red-social-c786b',
    storageBucket: 'red-social-c786b.firebasestorage.app',
    iosBundleId: 'com.manuelcastillo.vinilo',
  );
}
